version: '3.3'
services:
  backend:
    image: 'polarlightning/bitcoind:0.18.1'
    container_name: polar-n1-backend
    environment:
      USERID: '${USERID:-1000}'
      GROUPID: '${GROUPID:-1000}'
    hostname: backend
    command: >-
      bitcoind -server=1 -regtest=1
      -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526
      -debug=0 -zmqpubrawblock=tcp://0.0.0.0:28334
      -zmqpubrawtx=tcp://0.0.0.0:28335 -txindex=1 -dnsseed=0 -upnp=0
      -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcport=18443
    volumes:
      - './volumes/bitcoind/backend:/home/bitcoin/.bitcoin'
    expose:
      - '18443'
      - '18444'
      - '28334'
      - '28335'
    ports:
      - '18443:18443'
  alice:
    image: 'polarlightning/clightning:0.7.3'
    container_name: polar-n1-alice
    environment:
      USERID: '${USERID:-1000}'
      GROUPID: '${GROUPID:-1000}'
    hostname: alice
    command: >-
      lightningd --network=regtest --bitcoin-rpcuser=polaruser --bitcoin-rpcpassword=polarpass --bitcoin-rpcconnect=polar-n1-backend --bitcoin-rpcport=18443 --alias=alice --log-level=debug --plugin=/opt/c-lightning-rest/plugin.js --rest-port=8080 --rest-protocol=http
    restart: always
    volumes:
      - './volumes/clightning/alice:/home/clightning/.lightning'
    expose:
      - '8080'
      - '9735'
    ports:
      - '8081:8080'
  bob:
    image: 'polarlightning/lnd:0.8.0-beta'
    container_name: polar-n1-bob
    environment:
      USERID: '${USERID:-1000}'
      GROUPID: '${GROUPID:-1000}'
    hostname: bob
    command: >-
      lnd --noseedbackup --alias=bob --externalip=bob --tlsextradomain=bob
      --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080
      --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n1-backend --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n1-backend:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n1-backend:28335
    restart: always
    volumes:
      - './volumes/lnd/bob:/home/lnd/.lnd'
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8082:8080'
      - '10002:10009'
# docker build --build-arg CLN_VERSION=0.7.3 -t polarlightning/clightning:0.7.3 ./clightning
# bitcoin-cli -regtest -rpcconnect=polar-n1-backend -rpcport=18443 -rpcuser=polaruser -rpcpassword=polarpass getnewaddress
# bitcoin-cli -regtest -rpcconnect=polar-n1-backend -rpcport=18443 -rpcuser=polaruser -rpcpassword=polarpass generatetoaddress 10
# base64 /opt/c-lightning-rest/certs/access.macaroon
