name: CI

on:
  push:
    branches:
      - 'master'
      - 'release/*'
      - 'ci/*'
  pull_request:

jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # Run always on push, or on pull requests that are not from release or ci branches. This prevents duplaicate runs.
    if: github.event_name == 'push' || (startsWith(github.head_ref, 'release/') == false && startsWith(github.head_ref, 'ci/') == false)

    strategy:
      matrix:
        node_version: [20.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: ubuntu file watcher tweak
        if: matrix.os == 'ubuntu-latest'
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn

      - name: install dependencies
        run: yarn install --frozen-lockfile --network-timeout 1000000

      - name: lint code
        run: yarn lint

      - name: typescript compile
        run: yarn tsc

      - name: unit tests
        run: yarn test:ci

      - name: build check
        run: yarn build

      - name: coverage
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: electron build
        run: yarn package:ci
        if: startsWith(github.ref_name, 'release/')
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
