name: CI

on:
  push:
    branches:
      - 'master'
      - 'renovate/*'
      - 'release/*'
      - 'ci/*'
  pull_request:
    branches:
      - '*'
      - '!translations'
      - '!renovate/*'
      - '!release/*'
      - '!ci/*'
    types: [assigned, opened, synchronize, reopened]

jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: contains(github.event.head_commit.message, 'ci skip') == false

    strategy:
      matrix:
        node_version: [20.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: set git config
        run: |
          git config --global core.eol lf
          git config --global core.autocrlf false

      - name: ubuntu file watcher tweak
        if: matrix.os == 'ubuntu-latest'
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn

      - name: install dependencies
        run: yarn

      - name: lint code
        run: yarn lint

      - name: typescript compile
        run: yarn tsc

      - name: unit tests
        run: yarn test:ci

      - name: coverage
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: electron build
        run: yarn package:ci
        if: startsWith(github.ref, 'refs/heads/release/')
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
